### PR TITLE
DATALAB-292: Refactor 'Content Graph API' to 'Amanita'

### PR DESCRIPTION
**Pull request by jontutcher**
It'd be good to sort this quick-ish, as our renaming of the Content Graph API upstream has broken this service and it needs re-deploying asap :)

This is a breaking change because the `CONTENT_GRAPH_API_HOST` environment var has been renamed `AMANITA_HOST`. This may require config changes for deployment.

### CODE REVIEW

**Comment by jontutcher** [comment]
On closer inspection, it looks like the app is using its default config for looking for the Amanita URL (which is corrected in this refactor), so renaming the environment variable shouldn't have an impact.

**Comment by betandr** [comment]
@twindebank maybe they should change here now too because we're currently down so it'll not cause too much of an issue.

**Comment by jontutcher** [comment]
Will change the keys and add another commit here, and then won't squash when we merge - that way we don't have to deal with PRs but still keep the history :)

**Comment by twindebank** [comment]
You could still squash and include it in the extended commit message? Might make things a little cleaner

**Comment by tatiana** [comment]
Looks great, @jontutcher, PyCharm must have been extremely handy here! :shipit: 

It may be worth to update the first paragraph of the `README`, updating to Python 3 and it is used to expose the databases we use by Datalab:
```
API for the content graph. Implemented with the Python 2
[Flask](http://flask.pocoo.org/) microframework and running with
[Green Unicorn](http://gunicorn.org/) Python WSGI HTTP Server.```

**Comment by betandr** [comment]
:shipit: for new changes:
```
Make Amanita test stubs consistent with lowerCase API [8a300f1]
Refactor Amanita Interface for UpperCase keys [f57c081]
```

**Pull request merged**
